services:
  api:
    build:
      context: .
      target: builder
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=shopping_list
      - ENV=development
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: []  # Clear the default entrypoint
    command: go run main.go
    working_dir: /app  # Ensure working directory is set

  api-test:
    build:
      context: .
      target: builder
    working_dir: /app
    command: go test -v ./...
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=shopping_list
      - ENV=test
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=shopping_list
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
